lindsay/mesg/urls.py
from django.conf.urls import patterns, url

from mesg import views, feeds

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^user/config/$', views.user_config, name='user_config'),
    url(r'^message/create/$', views.create_message, name='create_message'),
    url(r'^message/(?P<message_id>\d+)/expire/$', views.expire_message,
        name='expire_message'),
    url(r'^message/(?P<message_id>\d+)/$', views.message, name='message'),
    url(r'^(?P<category_name>[\w\d_/-]+?)/$', views.category, name='category'),
    url(r'^(?P<category_name>[\w\d_/-]+?)/feed/$', feeds.CategoryFeed(),
        name='category_feed')
)

lindsay/mesg/forms.py
from django import forms
from mesg.models import Category

class CalendarWidget(forms.TextInput):
    class Media:
        css = {'all': ('jquery/jquery-ui.min.css',)}
        js = ('jquery/external/jquery/jquery.min.js',
              'jquery/jquery-ui.min.js',)

class CreateMessageForm(forms.Form):
    message_text = forms.CharField(label='Message', widget=forms.Textarea,
                                   max_length=200)

    expires_date = forms.DateField(label='Expire this message after',
                                   required=False,
                                   widget = CalendarWidget)

    choices = [('','----')]
    for division in Category.objects.filter(parent=None):
        choices.append((division.id, division.name))
        for subdivision in division.subcategories.all():
            choices.append((subdivision.id, '----' + subdivision.name))

    category = forms.ChoiceField(choices=choices, label='Category',
                                 required=True)


class UserConfigForm(forms.Form):
    choices = [('','----')]
    for division in Category.objects.filter(parent=None):
        choices.append((division.id, division.name))
        for subdivision in division.subcategories.all():
            choices.append((subdivision.id, '----' + subdivision.name))

    category = forms.ChoiceField(choices=choices, label='Category',
                                 required=True)
    

lindsay/mesg/templates/mesg/base.html
<!DOCTYPE html>

<html>
	<head>
		<title>{% block title %}{% endblock title %} LINDSaY</title>	

		{# For css and js files from forms #}
		{% block extrahead %}{% endblock extrahead %}
	</head>
	<body>
		<div class="session_header" id="loginstate">
			{% if user.is_authenticated %}
				Logged in as: {{ user.username }} - <a href="{% url 'mesg:logout' %}?next={% firstof request.path '/' %}">Logout</a>
			{% else %}
			<a href="{% url 'mesg:login' %}?next={% firstof request.path '/' %}">Login</a>
			{% endif %}
		</div>
		<hr />
		{% block body %}{% endblock body %}
	</body>
</html>

lindsay/mesg/templates/mesg/create_message.html
{% extends "mesg/base.html" %}


{% block title %}
Create message - 
{% endblock title %}

{% block extrahead %}
{{ form.media }}
<script>
$(function() {
	$( "#id_expires_date" ).datepicker({
		dateFormat: 'yy-mm-dd',
	});
});
</script>
{% endblock extrahead %}

{% block body %}
<form action="{% url 'mesg:create_message' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Post it" />
</form>
{% endblock body %}

lindsay/mesg/templates/mesg/division_base.html
{% extends "mesg/base.html" %}


{% block title}{% endblock title}


{% block body %}
<h1>
	{% block division_name %}{% endblock division_name %}
</h1>
<a href="{% url 'mesg:create_message' %}">Create message</a><br />
<a href="{% url 'mesg:division_feed' division_name=division.name %}">
	Feed
</a>
<hr />
{% block subdivisions_list %}{% endblock subdivisions_list %}
<hr />
{% block messages %}{% endblock messages %}
{% endblock body %}

lindsay/mesg/templates/mesg/message.html
{% extends "mesg/message_base.html" %}


{% block title %}
Message {{ message.pk }} - 
{% endblock title %}


{% block message_text %}
{{ message.message_text }}
{% endblock message_text %}

{% block files %}
<ul>
	{% for file in message.files.all %}
		<li><a href="{{ file.image.url }}">{{ file.image.name }}</a></li>
	{% endfor %}
</ul>
{% endblock files %}

{% block author_name %}
{{ message.author.username }}
{% endblock author_name %}


{% block pub_date %}
{{ message.pub_date|timesince }} ago ({{ message.pub_date|date:"c" }})
{% endblock pub_date %}


{% block expires_date %}
{% if message.expires_date != Null %}
	{{ message.expires_date|timeuntil }} ({{ message.expires_date|date:"c" }})
{% else %}
	Never - 
	<a href="{% url 'mesg:expire_message' message_id=message.id %}">
		Expire this message now
	</a>
{% endif %}
{% endblock expires_date %}


{% block category_breadcrumbs %}
<a href="{% url 'mesg:division' division_name=division.name %}">
	{{ division.name }}
</a> 
{% if subdivision %}
	&gt;&gt;
	<a href="{% url 'mesg:subdivision' division_name=division.name subdivision_name=subdivision.name %}">
		{{ subdivision.name }}
	</a>
{% endif %}
{% endblock category_breadcrumbs %}

lindsay/mesg/templates/mesg/message_base.html
{% extends "mesg/base.html" %}


{% block title %}{% endblock title %}


{% block body %}
{% block message_text %}{% endblock message_text %}
<hr />
{% block files %}{% endblock files %}
<hr />
Author: {% block author_name %}{% endblock author_name %}
<br />
Posted: {% block pub_date %}{% endblock pub_date %}
<br />
Expires in: {% block expires_date %}{% endblock expires_date %}
<br />
Posted in: {% block category_breadcrumbs %}{% endblock category_breadcrumbs %}
{% endblock body %}

lindsay/mesg/templates/mesg/subdivision.html
{% extends "mesg/subdivision_base.html" %}


{% block title %}
Messages for {{ subdivision.division.name}} {{ subdivision.name }} - 
{% endblock title %}


{% block subdivision_name %}
<a href="{% url 'mesg:division' division_name=subdivision.parent.name %}">
	{{ subdivision.parent.name }}
</a> &gt;&gt;
	{{ subdivision.name }}
{% endblock subdivision_name %}


{% block messages %}
<ul>
	{% for message in messages %}	
		<li>		
			<a href="{% url 'mesg:message' message_id=message.id %}">
				{{ message.message_text }}
			</a>
		</li>
	{% empty %}
		No messages available
	{% endfor %}	
</ul>
{% endblock messages %}

lindsay/mesg/templates/mesg/subdivision_base.html
{% extends "mesg/base.html" %}



{% block title %}{% endblock title %}



{% block body %}
<h1>
	{% block subdivision_name %}{% endblock subdivision_name %}
</h1>

<a href="{% url 'mesg:create_message' %}">Create message</a><br />
<a href="{% url 'mesg:subdivision_feed' division_name=division.name subdivision_name=subdivision.name %}">
	Feed
</a>
<hr />
{% block messages %}{% endblock messages %}
{% endblock body %}